### ISSUE TITLE
Add favicon img

### ISSUE THREAD

**Issue by y4sssh** [Yashdon999/Snake-Game#1]
Place favicon image as per website

**Comment by Pooja1672** [comment]
Hi @Yashdon999 I would like to work on this issue...Can you assign this to me ?

**Comment by y4sssh** [comment]
sure @Pooja1672  go ahead.

**Comment by nguyenthihuynhgiao** [comment]
Hi, can you assigned for me?

**Comment by y4sssh** [comment]
sure @nguyenthihuynhgiao go ahead.

**Comment by Pooja1672** [comment]
Hi @Yashdon999 , I fixed the issue of favicon image and now it is being displayed on the top
[
![Screenshot 2023-11-07 235731](https://github.com/Yashdon999/Snake-Game/assets/148313311/9bcef1b7-995e-4fd7-af03-927eebb0ce79)
](url)

I'm making PR for the same.
